sumdir -a sha2563 (a.k.a. annex) +checkdir
+ whitspace: 2 space soft indent

diff --git a/checkdir b/checkdir
--- a/checkdir
+++ b/checkdir
@@ -10,23 +10,23 @@ must() { "$@" || die "cannot $*"; }
 whisper() { local volume=$1; shift; [[ $opt_verbose -ge $volume ]] && yell "$@"; }
 
 toLowerCase() {
-	#perl -C -lne 'print uc';
-	tr '[:upper:]' '[:lower:]';
+  #perl -C -lne 'print uc';
+  tr '[:upper:]' '[:lower:]';
 }
 toUpperCase() {
-	#perl -C -lne 'print uc';
-	tr '[:lower:]' '[:upper:]';
+  #perl -C -lne 'print uc';
+  tr '[:lower:]' '[:upper:]';
 }
 
 
 ## CONST/CONFIGURATION:
 
 if [[ -z "$TMPDIR" || ! -d "$TMPDIR" ]]; then
-	if [[ -d '/dev/shm' ]]; then
-		export TMPDIR='/dev/shm';
-	else
-		export TMPDIR="$PWD";
-	fi
+  if [[ -d '/dev/shm' ]]; then
+    export TMPDIR='/dev/shm';
+  else
+    export TMPDIR="$PWD";
+  fi
 fi
 
 
@@ -35,26 +35,27 @@ fi
 
 SCRIPT_USAGE="${0##*/} [OPTIONS] [SUMFILE…]"
 SCRIPT_OPTIONS=(
-	"--help|help|-h  Show this help."
-	"--version       Show the script version."
-	"-a ALG          Set encryption algorithm."
-	"-e              Only check if files in SUMFILE exist, and output missing filenames."
-	"-l              Only output the SUMFILE path found/selected."
-	"-v              Show more verbose output."
+  "--help|help|-h  Show this help."
+  "--version       Show the script version."
+  "-a ALG          Set encryption algorithm."
+  "-e              Only check if files in SUMFILE exist, and output missing filenames."
+  "-l              Only output the SUMFILE path found/selected."
+  "-v              Show more verbose output."
 )
 SCRIPT_DESCRIPTION_LINES=(
-	"If no SUMFILE is specified, .*SHA256SUM* and *SHA256SUM* is globbed in the current directory, and the newest one is used."
+  "If no SUMFILE is specified, .*SHA256SUM* and *SHA256SUM* is globbed in the current directory, and the newest one is used."
 )
 SCRIPT_VERSIONS=(
-	"0.1.1 @1735249838  Add 'ALG' to '-a' in help.   b2sum=52aa3a44&size=5484" #nosum
-	"0.1.0 @1720381791  Show progress (percent an count).   b2sum=14b0e4c8&size=5484" #nosum
-	"0.0.7 @1670970409  Support for Bash 3.2.x; require tr instead of perl.   sum:db71df2c#a=b2,l=32;size:4959" #nosum
-	"0.0.6 @1670954755  Added option -l to output selected SUM file path.   sum:8e5df517#a=b2,l=32;size:4800" #nosum
-	"0.0.5 @1670874600  Allow checking only existence of files from SUMFILE (opt '-e').   sum:a4a54a563924caca275b3626734ee015#a=b2,l=128;size:5205" #nosum
-	"0.0.4 @1669927062  Detect sum algorithm from sum filename (supported: '*B2*' => b2; all else => sha256)" #nosum
-	"0.0.3 @1666205166  BSD/macOS support (Bash 3.2, shasum -a 256). Tests PASS @1666203994 with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)" #nosum
-	"0.0.2 @1664215277  Added help." #nosum
-	"0.0.1 @1664175524" #nosum
+  "0.2.0 @1772822488  Implement SHA256E.  b2sum=08778a02&size=6666" #nosum
+  "0.1.1 @1735249838  Add 'ALG' to '-a' in help.   b2sum=52aa3a44&size=5484" #nosum
+  "0.1.0 @1720381791  Show progress (percent an count).   b2sum=14b0e4c8&size=5484" #nosum
+  "0.0.7 @1670970409  Support for Bash 3.2.x; require tr instead of perl.   sum:db71df2c#a=b2,l=32;size:4959" #nosum
+  "0.0.6 @1670954755  Added option -l to output selected SUM file path.   sum:8e5df517#a=b2,l=32;size:4800" #nosum
+  "0.0.5 @1670874600  Allow checking only existence of files from SUMFILE (opt '-e').   sum:a4a54a563924caca275b3626734ee015#a=b2,l=128;size:5205" #nosum
+  "0.0.4 @1669927062  Detect sum algorithm from sum filename (supported: '*B2*' => b2; all else => sha256)" #nosum
+  "0.0.3 @1666205166  BSD/macOS support (Bash 3.2, shasum -a 256). Tests PASS @1666203994 with GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)" #nosum
+  "0.0.2 @1664215277  Added help." #nosum
+  "0.0.1 @1664175524" #nosum
 )
 SCRIPT_VERSION="${SCRIPT_VERSIONS[0]}"
 
@@ -62,183 +63,219 @@ SCRIPT_VERSION="${SCRIPT_VERSIONS[0]}"
 ## METHODS:
 
 showHelp() {
-	echo "USAGE: $SCRIPT_USAGE";
-	echo "";
-	echo "OPTIONS:";
-	local opt;
-	for opt in "${SCRIPT_OPTIONS[@]}"; do
-		echo "  ${opt}"
-	done
-	echo "";
-	echo "DESCRIPTION:";
-	for line in "${SCRIPT_DESCRIPTION_LINES[@]}"; do
-		echo "  ${line}"
-	done
+  echo "USAGE: $SCRIPT_USAGE";
+  echo "";
+  echo "OPTIONS:";
+  local opt;
+  for opt in "${SCRIPT_OPTIONS[@]}"; do
+    echo "  ${opt}"
+  done
+  echo "";
+  echo "DESCRIPTION:";
+  for line in "${SCRIPT_DESCRIPTION_LINES[@]}"; do
+    echo "  ${line}"
+  done
 }
 
 confirm() {
-	local prompt="$1";
-	local answer="$2";
-	local REPLY;
-	local defaultYes=true
-	if [[ $answer =~ [Nn] ]]; then
-		defaultYes=false
-		options='y/N'
-	else
-		options='Y/n'
-	fi
-	read -n1 -p "${prompt} (${options}) ";
-	if [[ $defaultYes == true ]]; then
-		[[ -z $REPLY || $REPLY =~ [Yy] ]];
-		return
-	else
-		[[ $REPLY =~ [Yy] ]];
-		return
-	fi
+  local prompt="$1";
+  local answer="$2";
+  local REPLY;
+  local defaultYes=true
+  if [[ $answer =~ [Nn] ]]; then
+    defaultYes=false
+    options='y/N'
+  else
+    options='Y/n'
+  fi
+  read -n1 -p "${prompt} (${options}) ";
+  if [[ $defaultYes == true ]]; then
+    [[ -z $REPLY || $REPLY =~ [Yy] ]];
+    return
+  else
+    [[ $REPLY =~ [Yy] ]];
+    return
+  fi
 }
 
+if ! command -v sha256sum &>/dev/null; then
+  if command -v shasum &>/dev/null; then
+    sha256sum() { shasum -a 256 "$@"; }
+  fi
+fi
+
 initializeSumCommand() {
-	# NOTE: Each command MUST support the '--check SUMFILE' option.
-	opt_algorithm="$(echo "$opt_algorithm" | toLowerCase)";
-	case $opt_algorithm in
-		sha*) sumCommand=(sha256sum);
-			if ! command -v sha256sum &>/dev/null; then
-				if command -v shasum &>/dev/null; then
-					sumCommand=(shasum -a 256);
-				else
-					die "Missing checksum software: sha256sum or shasum.";
-				fi
-			fi
-			;;
-		b2*|blake*) sumCommand=(b2sum);;
-		*) die "Unknown sum algorithm '${opt_algorithm}'.";;
-	esac
-	if command -v "${sumCommand[0]}" &>/dev/null; then
-		whisper 1 "Using $(which "${sumCommand[0]}")";
-	else
-		die "Missing checksum software: ${sumCommand[0]}.";
-	fi
+  # NOTE: Each command MUST support the '--check SUMFILE' option.
+  opt_algorithm="$(echo "$opt_algorithm" | toLowerCase)";
+  case $opt_algorithm in
+    sha256e|*annex) opt_algorithm=sha256e;
+      if ! command -v sha256sum &>/dev/null; then
+        die "Missing checksum software: sha256sum or shasum.";
+      fi
+      sumCommand=(checksumSHA256E);
+      ;;
+    sha*) sumCommand=(sha256sum);
+      if ! command -v sha256sum &>/dev/null; then
+        die "Missing checksum software: sha256sum or shasum.";
+      fi
+      ;;
+    b2*|blake*) sumCommand=(b2sum);;
+    *) die "Unknown sum algorithm '${opt_algorithm}'.";;
+  esac
+  if command -v "${sumCommand[0]}" &>/dev/null; then
+    whisper 1 "Using $(which "${sumCommand[0]}")";
+  else
+    die "Missing checksum software: ${sumCommand[0]}.";
+  fi
 }
 
 getSumFile() {
-	local match;
-	match="$(ls -1t .*SUM* 2>/dev/null)" \
-		|| match="$(ls -t *SUM* 2>/dev/null)" \
-		|| return $?;
+  local match;
+  match="$(ls -1t .*SUM* 2>/dev/null)" \
+    || match="$(ls -t *SUM* 2>/dev/null)" \
+    || return $?;
 
-	echo -en "$match" | head -1
+  echo -en "$match" | head -1
 }
 
 countFilesInSumFile() {
-	local sumFile="$1"
-	grep -Ecv '^\s*(#.*)\s*$' "$sumFile";
+  local sumFile="$1"
+  grep -Ecv '^\s*(#.*)\s*$' "$sumFile";
 }
+
 describeSumFile() {
-	local sumFile="$1";
-	local fileCount="$2";
-	[[ -z $fileCount ]] && fileCount="$(countFilesInSumFile "$sumFile")";
-	local dirCount="$(grep -Ec '^[a-f0-9]+  .*/' "$sumFile")";
+  local sumFile="$1";
+  local fileCount="$2";
+  [[ -z $fileCount ]] && fileCount="$(countFilesInSumFile "$sumFile")";
+  local dirCount="$(grep -Ec '^[a-f0-9]+  .*/' "$sumFile")";
 
-	local description="${fileCount} files";
+  local description="${fileCount} files";
 
-	if [[ $dirCount -gt 0 ]]; then
-		description+="; descends into directories";
-	fi;
+  if [[ $dirCount -gt 0 ]]; then
+    description+="; descends into directories";
+  fi;
 
-	echo -n "$description";
+  echo -n "$description";
 }
+
+checksumSHA256E() {
+  local sumfile path basename size sum ext baseKey status
+  while [[ $# -gt 0 ]]; do
+    case $1 in
+      --|--check) shift; continue;;
+      *) sumfile="$1";
+    esac
+    shift
+  done
+  while read -r key path; do
+    [[ $key =~ ^\s*# ]] && continue;
+    basename="$(basename "$path")"
+    size="$(du -L -b "$path" | awk '{ print $1 }')"
+    sum="$(sha256sum "$path" | awk '{ print $1 }')"
+    baseKey="SHA256E-s${size}--${sum}"
+    if [[ ${key:0:${#baseKey}} == $baseKey ]]; then
+      status=OK
+    else
+      status=FAILED
+    fi
+    echo "${path}: ${status}"
+  done <"$sumfile"
+}
+export -f checksumSHA256E
 
 ## Giving it a descriptive name, because (with option -e) it shows up in the "full" output to an
 ## interactive shell.
 checkdir_doPathsInSumFileExist() {
-	local sumFile="$1"; shift;
-	local numTotal=0 numPresent=0 numMissing=0;
-	local exitStatus=0;
+  local sumFile="$1"; shift;
+  local numTotal=0 numPresent=0 numMissing=0;
+  local exitStatus=0;
 
-	whisper 2 "About to read sumfile(${sumFile}) line by line in Bash.";
-	local hash path;
-	while read hash path; do
-		if [[ -z $hash || -z "$path" || $hash =~ ^[[:space:]]*# ]]; then
-			whisper 2 "Skipping commented line: ${hash} ${path}";
-			continue;
-		fi;
+  whisper 2 "About to read sumfile(${sumFile}) line by line in Bash.";
+  local hash path;
+  while read hash path; do
+    if [[ -z $hash || -z "$path" || $hash =~ ^[[:space:]]*# ]]; then
+      whisper 2 "Skipping commented line: ${hash} ${path}";
+      continue;
+    fi;
 
-		let numTotal++;
-		if [[ -e "$path" ]]; then
-			let numPresent++;
-			echo "EXISTS: ${path}";
-		else
-			let numMissing++;
-			exitStatus=1;
-			echo "MISSING: ${path}";
-		fi
-	done <"$sumFile"
+    let numTotal++;
+    if [[ -e "$path" ]]; then
+      let numPresent++;
+      echo "EXISTS: ${path}";
+    else
+      let numMissing++;
+      exitStatus=1;
+      echo "MISSING: ${path}";
+    fi
+  done <"$sumFile"
 
-	if [[ $numMissing -gt 0 ]]; then
-		yell "Missing ${numMissing} files.";
-	fi
+  if [[ $numMissing -gt 0 ]]; then
+    yell "Missing ${numMissing} files.";
+  fi
 
-	return $exitStatus;
+  return $exitStatus;
 }
 
 main() {
-	local sumFile="$1";
-	if [[ -z "$sumFile" ]]; then
-		sumFile="$(getSumFile)" || die "No hash file to check against. Run sumdir to make one.";
-	fi
+  local sumFile="$1";
+  if [[ -z "$sumFile" ]]; then
+    sumFile="$(getSumFile)" || die "No hash file to check against. Run sumdir to make one.";
+  fi
 
-	if [[ $sumFile =~ [bB]2 ]]; then
-		opt_algorithm=b2;
-	else
-		opt_algorithm=sha256;
-	fi
+  if [[ $sumFile =~ [bB]2 ]]; then
+    opt_algorithm=b2;
+  elif [[ $sumFile =~ SHA256E ]]; then
+    opt_algorithm=sha256e;
+  else
+    opt_algorithm=sha256;
+  fi
 
-	checkOutputCacheFile="${TMPDIR}/.checking.${sumFile##*/}.${RANDOM}.log";
-	local fileCount="$(countFilesInSumFile "$sumFile")";
-	yell "Checking files against $sumFile ($(describeSumFile "$sumFile" "$fileCount"))";
+  checkOutputCacheFile="${TMPDIR}/.checking.${sumFile##*/}.${RANDOM}.log";
+  local fileCount="$(countFilesInSumFile "$sumFile")";
+  yell "Checking files against $sumFile ($(describeSumFile "$sumFile" "$fileCount"))";
 
-	## PREPARING EXECUTION:
-	checkCommand=();
-	if [[ $opt_check_exists_only != 'true' ]]; then
-		initializeSumCommand;
-		checkCommand+=("${sumCommand[@]}" --check "$sumFile");
-	else
-		checkCommand+=(checkdir_doPathsInSumFileExist "$sumFile");
-	fi
+  ## PREPARING EXECUTION:
+  checkCommand=();
+  if [[ $opt_check_exists_only != 'true' ]]; then
+    initializeSumCommand;
+    checkCommand+=("${sumCommand[@]}" --check "$sumFile");
+  else
+    checkCommand+=(checkdir_doPathsInSumFileExist "$sumFile");
+  fi
 
-	## EXECUTION:
-	# WISH (B) 2024-07-07 parallelize file hash check
-	# DONE x 2024-07-07 (A) 2024-07-07 Show progress
-	local checkOutput="$("${checkCommand[@]}" | {
-		outputLineCount=0;
-		while read outputLine; do
-			let 'outputLineCount++';
-			echo "$outputLine";
-			>&2 echo -n "  $((100 * outputLineCount / fileCount))% (${outputLineCount} files checked)       "$'\r'; # space at the end to blank out long numbers
-		done;
-		>&2 echo;
-	};)";
-	
-	checkStatus=$?;
+  ## EXECUTION:
+  # WISH (B) 2024-07-07 parallelize file hash check
+  # DONE x 2024-07-07 (A) 2024-07-07 Show progress
+  local checkOutput="$("${checkCommand[@]}" | {
+    outputLineCount=0;
+    while read outputLine; do
+      let 'outputLineCount++';
+      echo "$outputLine";
+      >&2 echo -n "  $((100 * outputLineCount / fileCount))% (${outputLineCount} files checked)       "$'\r'; # space at the end to blank out long numbers
+    done;
+    >&2 echo;
+  };)";
+  
+  checkStatus=$?;
 
-	## HANDLE OUTPUT:
-	if echo "$checkOutput" \
-		| tee "${checkOutputCacheFile}" \
-		| grep 'FAILED\|MISSING'; then
-		yell "";
-		yell "(Showing only failures…)";
-		[[ -t 0 ]] \
-			&& confirm "See full output?" 'n' \
-			&& cat <(echo "### output from '${checkCommand[*]}':") "$checkOutputCacheFile" <(echo -e "\n### sum file data being checked:") "$sumFile" | less
-	elif [[ $checkStatus != 0 ]]; then
-		yell "✗ Finished with problems.";
-	else
-		yell "✓ All OK";
-	fi
+  ## HANDLE OUTPUT:
+  if echo "$checkOutput" \
+    | tee "${checkOutputCacheFile}" \
+    | grep 'FAILED\|MISSING'; then
+    yell "";
+    yell "(Showing only failures…)";
+    [[ -t 0 ]] \
+      && confirm "See full output?" 'n' \
+      && cat <(echo "### output from '${checkCommand[*]}':") "$checkOutputCacheFile" <(echo -e "\n### sum file data being checked:") "$sumFile" | less
+  elif [[ $checkStatus != 0 ]]; then
+    yell "✗ Finished with problems.";
+  else
+    yell "✓ All OK";
+  fi
 
-	[[ -e "$checkOutputCacheFile" ]] && rm "$checkOutputCacheFile"
+  [[ -e "$checkOutputCacheFile" ]] && rm "$checkOutputCacheFile"
 
-	return $checkStatus;
+  return $checkStatus;
 }
 
 
@@ -252,16 +289,16 @@ sumCommand=();
 sumFileArgs=();
 
 while [[ $# -gt 0 ]]; do
-	case $1 in
-		--help|help|-h) showHelp; exit;;
-		-a) opt_algorithm="$2"; shift;;
-		-e) opt_check_exists_only=true;;
-		-l) getSumFile; exit;;
-		-v) let opt_verbose++;;
-		--version) echo "v${SCRIPT_VERSION%%  *} ($0)"; exit;;
-		*) sumFileArgs+=("$1");;
-	esac
-	shift;
+  case $1 in
+    --help|help|-h) showHelp; exit;;
+    -a) opt_algorithm="$2"; shift;;
+    -e) opt_check_exists_only=true;;
+    -l) getSumFile; exit;;
+    -v) let opt_verbose++;;
+    --version) echo "v${SCRIPT_VERSION%%  *} ($0)"; exit;;
+    *) sumFileArgs+=("$1");;
+  esac
+  shift;
 done
 
 main "${sumFileArgs[@]}";
diff --git a/sumdir b/sumdir
--- a/sumdir
+++ b/sumdir
@@ -17,6 +17,7 @@
   SCRIPT_EXAMPLES+=("sumdir -r -exec " "Output an extra column after filename with the result of … (see \`find -exec\`)")
   SCRIPT_PURPOSE="Coordinates the generation and output of many checksums."
   SCRIPT_VERSIONS=(
+    "0.2.0  @1772822542  Implement SHA256E sum. Abstract sha256sum polyfill.  b2sum=4da8a9fc&size=16197" #nosum
     "0.1.8  @1760374334  Refactor execution into main function. Repair & extend documentation.  b2sum=4f000838&size=15179" #nosum
     "0.1.7  @1706565414  Add \`--\` before filenames, in case paths begin with \`-\`.  b2sum=59241fc0&size=13370" #nosum
     "0.1.6  @1699561902  Template can contain output path. More documentation.  b2sum=6ef9ea3c&size=13289" #nosum
@@ -145,8 +146,10 @@
       let 'exampleIndex++';
     done
   }
+}
 
-  ## APPLICATION:
+## APPLICATION:
+{
   main() {
     local inputDirectories=();
 
@@ -250,7 +253,7 @@
       {
         echo "# Generated ${date} by ${SCRIPT_NAME} ${SCRIPT_VERSION_NICE}  (called as \`${CALLED_AS_WITH_ARGS}\`)";
         echo "# Same as:  ${sumCommand[*]} FILENAMES";
-        echo "# To check file integrity, run:  ${checkCommand[*]} -c ${outputFilePath}";
+        echo "# To check file integrity, run:  ${checkCommand[*]} ${outputFilePath}";
         local dirPath;
         if [[ $opt_should_include_location_in_output == true ]]; then
           dirPath="${PWD}"
@@ -318,23 +321,26 @@
     jobExecutor=();
     algoUpper='';
     case "$(echo -n "$opt_algorithm" | toLowerCase)" in
-      sha*) opt_algorithm=sha256;
-        sumCommand=(sha256sum);
-        if ! command -v ${sumCommand[0]} &>/dev/null; then
-          if command -v shasum &>/dev/null; then
-            sumCommand=(shasum -a 256);
-          else
-            die "Missing checksum software: sha256sum or shasum.";
-          fi
+      sha256e|*annex) opt_algorithm=sha256e;
+        if ! command -v sha256sum &>/dev/null; then
+          die "Missing checksum software: sha256sum or shasum.";
         fi
-        checkCommand=("${sumCommand[@]}");
+        sumCommand=(sumSHA256E);
+        checkCommand=(checkdir);
+        ;;
+      sha*) opt_algorithm=sha256;
+        if ! command -v sha256sum &>/dev/null; then
+          die "Missing checksum software: sha256sum or shasum.";
+        fi
+        sumCommand=(sha256sum);
+        checkCommand=("${sumCommand[@]}" -c);
         if [[ ${#opt_list_sha_opts[@]} -gt 0 ]]; then
           sumCommand+=("${opt_list_sha_opts[@]}");
         fi
         ;;
       b2*|blake*) opt_algorithm=b2;
         sumCommand=(b2sum);
-        checkCommand=("${sumCommand[@]}");
+        checkCommand=("${sumCommand[@]}" -c);
         if [[ ${#opt_list_b2_opts[@]} -gt 0 ]]; then
           sumCommand+=("${opt_list_b2_opts[@]}");
         fi
@@ -356,6 +362,28 @@
       jobExecutor=(xargs -0); return 0; fi;
     die "Missing parallel and xargs.";
   }
+  sumSHA256E() {
+    local path basename size sum ext maxExtlen=10
+    while [[ $# -gt 0 ]]; do
+      if [[ $1 == '--' ]]; then
+        shift;
+        continue;
+      fi
+      path="$1"
+      shift
+      basename="$(basename "$path")"
+      size="$(du -L -b "$path" | awk '{ print $1 }')"
+      sum="$(sha256sum "$path" | awk '{ print $1 }')"
+      ext="${path##*.}"
+      if [[ $ext == $path || $ext == $basename || ${#ext} -gt $maxExtlen ]] then
+        ext=''
+      else
+        ext=".${ext}"
+      fi
+      echo "SHA256E-s${size}--${sum}${ext}  ${path}"
+    done
+  }
+  export -f sumSHA256E
 }
 
 ## PLUMBING:
@@ -410,6 +438,10 @@
     done
     fullPath "${linkPath}";
   }
+  if ! command -v sha256sum &>/dev/null && command -v shasum &>/dev/null; then
+    sha256sum() { shasum -a 256 "$@"; }
+    export -f sha256sum;
+  fi
 }
 
 ## CONFIGURATION:
